[project]
name = "carfax-agent"
version = "0.1.0"
description = "Fetch carfax report using the VIN number"
requires-python = ">=3.10"
dependencies = [
    "a2a-sdk>=0.2.5",
    "pydantic",
    "python-dotenv",
    "google-adk>=1.2.1",
    "uvicorn",
    "google-generativeai",
] 
