[project]
name = "carfax-agent"
version = "0.1.0"
description = "A Carfax agent for fetching vehicle reports using VIN number."
requires-python = ">=3.10"
dependencies = [
    "a2a-sdk>=0.2.5",
    "google-adk>=1.2.1",
    "python-dotenv",
    "uvicorn",
] 
